### ISSUE TITLE
Erro de instalação no Windows 10

### ISSUE THREAD

**Issue by CalixtoNeto** [AlertaDengue/PySUS#13]
Failed building wheel for PySUS
  Running setup.py clean for PySUS
Failed to build PySUS
Installing collected packages: PySUS
  Running setup.py install for PySUS ... error
    Complete output from command C:\ProgramData\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\CALIXTO\\AppData\\Local\\Temp\\pip-install-65y7p2b6\\PySUS\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\CALIXTO\AppData\Local\Temp\pip-record-iwk6emqg\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\pysus
    copying pysus\__init__.py -> build\lib.win-amd64-3.7\pysus
    creating build\lib.win-amd64-3.7\pysus\online_data
    copying pysus\online_data\CIHA.py -> build\lib.win-amd64-3.7\pysus\online_data
    copying pysus\online_data\CNES.py -> build\lib.win-amd64-3.7\pysus\online_data
    copying pysus\online_data\SIA.py -> build\lib.win-amd64-3.7\pysus\online_data
    copying pysus\online_data\SIH.py -> build\lib.win-amd64-3.7\pysus\online_data
    copying pysus\online_data\SIM.py -> build\lib.win-amd64-3.7\pysus\online_data
    copying pysus\online_data\sinasc.py -> build\lib.win-amd64-3.7\pysus\online_data
    copying pysus\online_data\__init__.py -> build\lib.win-amd64-3.7\pysus\online_data
    creating build\lib.win-amd64-3.7\pysus\preprocessing
    copying pysus\preprocessing\decoders.py -> build\lib.win-amd64-3.7\pysus\preprocessing
    copying pysus\preprocessing\sinan.py -> build\lib.win-amd64-3.7\pysus\preprocessing
    copying pysus\preprocessing\__init__.py -> build\lib.win-amd64-3.7\pysus\preprocessing
    creating build\lib.win-amd64-3.7\pysus\tests
    copying pysus\tests\test_decoders.py -> build\lib.win-amd64-3.7\pysus\tests
    copying pysus\tests\test_sinan.py -> build\lib.win-amd64-3.7\pysus\tests
    copying pysus\tests\test_utilities.py -> build\lib.win-amd64-3.7\pysus\tests
    copying pysus\tests\__init__.py -> build\lib.win-amd64-3.7\pysus\tests
    creating build\lib.win-amd64-3.7\pysus\utilities
    copying pysus\utilities\readdbc.py -> build\lib.win-amd64-3.7\pysus\utilities
    copying pysus\utilities\_build_readdbc.py -> build\lib.win-amd64-3.7\pysus\utilities
    copying pysus\utilities\__init__.py -> build\lib.win-amd64-3.7\pysus\utilities
    creating build\lib.win-amd64-3.7\pysus\tests\test_data
    copying pysus\tests\test_data\test_ciha.py -> build\lib.win-amd64-3.7\pysus\tests\test_data
    copying pysus\tests\test_data\test_sia.py -> build\lib.win-amd64-3.7\pysus\tests\test_data
    copying pysus\tests\test_data\test_sih.py -> build\lib.win-amd64-3.7\pysus\tests\test_data
    copying pysus\tests\test_data\test_sim.py -> build\lib.win-amd64-3.7\pysus\tests\test_data
    copying pysus\tests\test_data\test_sinasc.py -> build\lib.win-amd64-3.7\pysus\tests\test_data
    copying pysus\tests\test_data\__init__.py -> build\lib.win-amd64-3.7\pysus\tests\test_data
    copying pysus\utilities\blast.c -> build\lib.win-amd64-3.7\pysus\utilities
    copying pysus\utilities\_readdbc.c -> build\lib.win-amd64-3.7\pysus\utilities
    copying pysus\utilities\blast.h -> build\lib.win-amd64-3.7\pysus\utilities
    copying pysus\utilities\blast.o -> build\lib.win-amd64-3.7\pysus\utilities
    copying pysus\utilities\_readdbc.o -> build\lib.win-amd64-3.7\pysus\utilities
    copying pysus\utilities\_readdbc.cpython-36m-x86_64-linux-gnu.so -> build\lib.win-amd64-3.7\pysus\utilities
    running build_ext
    generating cffi module 'build\\temp.win-amd64-3.7\\Release\\_readdbc.c'
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    building '_readdbc' extension
    creating build\temp.win-amd64-3.7\Release\build
    creating build\temp.win-amd64-3.7\Release\build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release\build\temp.win-amd64-3.7\Release
    creating build\temp.win-amd64-3.7\Release\pysus
    creating build\temp.win-amd64-3.7\Release\pysus\utilities
    creating build\temp.win-amd64-3.7\Release\pysus\utilities\c-src
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.20.27508\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ipysus/utilities\c-src/ -IC:\ProgramData\Anaconda3\include -IC:\ProgramData\Anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.20.27508\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /Tcbuild\temp.win-amd64-3.7\Release\_readdbc.c /Fobuild\temp.win-amd64-3.7\Release\build\temp.win-amd64-3.7\Release\_readdbc.obj
    _readdbc.c
    build\temp.win-amd64-3.7\Release\_readdbc.c(523): fatal error C1083: NÆo ‚ poss¡vel abrir arquivo incluir: 'unistd.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.20.27508\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "C:\ProgramData\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\CALIXTO\\AppData\\Local\\Temp\\pip-install-65y7p2b6\\PySUS\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\CALIXTO\AppData\Local\Temp\pip-record-iwk6emqg\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\CALIXTO\AppData\Local\Temp\pip-install-65y7p2b6\PySUS\

**Comment by fccoelho** [comment]
@CalixtoNeto , infelizmente não temos como testar ou mesmo criar um pacote compilado para Windows.
o desenvolvimento do PySUS é feito em Linux. 

O problema que aparece é a falha na compilação da extensão em C que é necessária para lidar com arquivos DBC.

**Comment by CalixtoNeto** [comment]
obrigado pelo esclarecimento
