### ISSUE TITLE
Adicionar possibilidade de Download para Tabelas SP no SIH

### ISSUE THREAD

**Issue by fccoelho** [AlertaDengue/PySUS#134]
Arquivos como este:
ftp://anonymous@ftp.datasus.gov.br/dissemin/publicos/SIHSUS/200801_/Dados/SPCE0804.dbc

devem ser adicionado às opções de Download caso o `SIH_GROUP='SP'` seja indicado.

**Comment by fccoelho** [comment]
Os grupos `RJ`, `ER` e `CH` também devem ser opções.

**Comment by joelmamoser** [comment]
So, in this case, to download SP version, how can I add this information to the original code?
https://github.com/AlertaDengue/PySUS/blob/master/pysus/Notebooks/Analyzing%20SIH.ipynb

from pysus.online_data import parquets_to_dataframe
from pysus.online_data.SIH import download

**SIH_GROUP='SP'**

TO = download('to', 2009, 10)

dfTO = parquets_to_dataframe(TO)

dfTO.head()

**Comment by luabida** [comment]
Hello @joelmamoser, after updating the PySUS version to 0.9.3, you can just add the group to the function call after the month:

```py
TO = download('to', 2009, 10, SIH_GROUP)
```

If you want to check the arguments' order, please refer [here](https://github.com/AlertaDengue/PySUS/blob/master/pysus/online_data/SIH.py#L16)

**Comment by joelmamoser** [comment]
Thank you so much! 
May I suggest or ask for anything else? Is it possible to download the entire year instead of just one month at a time, like we do  using R package?

install.packages("microdatasus")
library(microdatasus)
dados_sih <- fetch_datasus(year_start = 2022,
year_end = 2022,
**month_start = 1,
month_end = 3,**
uf = "SC",
information_system = "SIH-SP")

**Comment by luabida** [comment]
@joelmamoser yes, it is possible. You could pass the months in a list:

```py
months = [1,2,3,4,5,6,7,8,9,10,11,12] # or
months = list(range(1,12+1))

TO = download('to', 2009, months, SIH_GROUP)
```

**Comment by joelmamoser** [comment]
Hey! How canI define in the code to fetch records only from the state of Santa Catarina?

**Comment by luabida** [comment]
Hello @joelmamoser, the first parameter in the method is the state, so you could change it like this:

```py
SC = download('SC', 2009, months, SIH_GROUP)
```

please let me know if you are able to download the DBCs for Santa Catarina
