### ISSUE TITLE
No module named 'pysus.utilities._readdbc'

### ISSUE THREAD

**Issue by marceloandriolli** [AlertaDengue/PySUS#16]
I'm using ubuntu 18.04 and I have already installed `libffi-dev`, but when I try to do `import from pysus.utilities.readdbc import read_dbc` I got this error: 

```<ipython-input-1-7723051aeb1f> in <module>
----> 1 from pysus.utilities.readdbc import read_dbc

~/.pyenv/versions/3.7.3/envs/informacao_salva/lib/python3.7/site-packages/pysus/utilities/readdbc.py in <module>
     10 from dbfread import DBF
     11 
---> 12 from pysus.utilities._readdbc import ffi, lib
     13 
     14 

ModuleNotFoundError: No module named 'pysus.utilities._readdbc'```

**Comment by marcelo-ventura** [comment]
Same sort of problem here using macOs Catalina, upvoted.

`utilities/_readdbc.abi3.so, 2): no suitable image found.`

**Comment by fccoelho** [comment]
To help everybody having issues compiling PySUS C-extension, I have created a [dockerfile](https://github.com/AlertaDengue/PySUS/blob/master/dockerfile).

Basic instructions on how to use it are in the project's [README](https://github.com/AlertaDengue/PySUS/blob/master/README.md).

If you don't know what docker containers  are please refer to their [website](https://www.docker.com/). All you have to do is install docker on your system and follow the instructions on the README.

Another possibility, perhaps less technically demanding, is to use Gigantum. I have created this [public tutorial](https://gigantum.com/fccoelho/pysus-tutorial) which can be downloaded and used locally  by anyone. (Gigantum also uses docker, but hides it from the user)

**Comment by rdenadai** [comment]
Don't know cffi enough to tell the whole story, but, looking at my "**site-packages/pysus/utilities**" dir, i saw the _readdbc.so with the name "**_readdbc.cpython-37m-x86_64-linux-gnu.so**".

So, i rename the file to **_readdbc.so** and now it works like a charm.

**Comment by rdenadai** [comment]
@fccoelho uma coisa que percebi, e esse erro parece estar relacionado é que aparentemente a compilação do _readdbc esta sendo feita para python 3.7 (conforme nome do arquivo **cpython-37m**), entretanto estou usando na minha máquina python 3.8.2.

No meu ambiente uso o **pyenv** para registrar a versão do python usada. Compilei manualmente o código do readdbc usando o python 3.8.2 e substiui no arquivo (ao compilar ele gerou o arquivo **cpython-38**).

Talvez tenha alguma relação com alguma lib em C do python que acabou não registrando corretamente no SO usando o pyenv... não sei o ambiente do pessoal anterior.

até

**Comment by fccoelho** [comment]
O arquivo `cpython -37m...` deve ter sido gerado em uma compilação do PySUS antes da sua atualização do Python para 3.8

**Comment by rdenadai** [comment]
@fccoelho então, na verdade minha versão do python sempre foi a 3.8... no meu caso, deve ser algum resquicio da versão 3.7 (tb instalada va pyenv) que ficou.

**Comment by fccoelho** [comment]
As mudanças incluídas no commit 40f8b5dc parecem haver consertado este bug. Fechando esta issue.
