### ISSUE TITLE
Importar a base de dados

### ISSUE THREAD

**Issue by AlineGobbi** [AlertaDengue/PySUS#184]
Consegui instalar o pysus no google colab, mas quando coloco o comando como na documentação da erro. 

from pysus.ftp.databases.sinasc import SINASC

tentei esse tbm e tbm deu erro:  from pysus.online_data.SIM import download

![Captura de tela 2024-01-05 075218](https://github.com/AlertaDengue/PySUS/assets/95905428/4972472e-568b-4f54-ae08-bcb0854cc11d)
![Captura de tela 2024-01-05 075332](https://github.com/AlertaDengue/PySUS/assets/95905428/cd399470-5a46-41ac-ab73-e97099e6672b)

**Comment by rg-cefetrj** [comment]
Tive o mesmo problema. 
O código em questão foi introduzido no commit https://github.com/AlertaDengue/PySUS/commit/67fca920d744f82dc760bf6217746290d15d9c96.

Como workaround, você pode usar a versão anterior com: 
!pip install PySUS==0.12.0

**Comment by fccoelho** [comment]
A versão do Python no Colab é meio antiga:
![image](https://github.com/AlertaDengue/PySUS/assets/140123/8574641b-0922-47c2-85e3-51e3fea955ea)

Em abril, finalmente vão atualizar:
![image](https://github.com/AlertaDengue/PySUS/assets/140123/37472868-a5d2-4378-9a13-52b87d21bdfc)
