### ISSUE TITLE
bump max python version to 3.12x

### ISSUE THREAD

**Issue by fccoelho** [AlertaDengue/PySUS#196]
default python version in many Linux distros are now 3.12.x. So to stay compatible we need a release that can be installed on this version.

**Comment by turicas** [comment]
Should just change `pyproject.toml` or force this version on the provided `Dockerfile` also (it does not seem to specify any Python version AFAIK)?

**Comment by fccoelho** [comment]
Sure, we just need to double check if all dependencies are ok with the most recent version of Python, and then cut a release. It would be nice to finish issues 191 and 195 befor a new release, tough.
