### ISSUE TITLE
Error in download Function of pysus v0.10.4 with Unpackable File Names

### ISSUE THREAD

**Issue by Twetler** [AlertaDengue/PySUS#199]
##  How to reproduce my error
Using version 0.10.4
`from pysus.online_data.SIA import download`
`download('BA', 2024, 4, groups = ["BI"])`

![image](https://github.com/AlertaDengue/PySUS/assets/66122150/082feaa7-fd8f-42fb-b5d0-d0bfaaba02d4)
 Which refers to:

```
def format(self, file: File) -> tuple:
        if file.extension.upper() in [".DBC", ".DBF"]:
            digits = ''.join([d for d in file.name if d.isdigit()])
            print("This",file.name.split(digits))
            chars, _ = file.name.split(digits) # This line crashes
            year, month = digits[:2], digits[2:]
            group, _uf = chars[:-2].upper(), chars[-2:].upper()
            return group, _uf, zfill_year(year), month
        return ()
```
After receiving lots of values like this ['BIMG', ''] which is easily unpacked, **I got a ['BIMG2305_1'] which can't be unpacked** as a tuple.

My shortfix was to extract the List's first item [0] however I don't know if this solution can be used for all files. It also raised a doubt if this logic is reproduced in the other libraries.

**Comment by fccoelho** [comment]
It seems that now Datasus is splitting the larger files in two for the bigger states: half of the data goes into `BIMG2305_1` and the other half into `BIMG2305_2` in your example. @luabida can you add a rule to handle this?
