### ISSUE TITLE
Direct Download of SUS databases

### ISSUE THREAD

**Issue by fccoelho** [AlertaDengue/PySUS#2]
Implement direct download of databases publicly accessible through the web. We should start with SINASC to complement the DBC decompressing functionality

**Comment by fccoelho** [comment]
The Starting Link is this http://www2.datasus.gov.br/DATASUS/index.php?area=0901&item=1&acao=28
We need to automated the dowanload of it all.

**Comment by rafaelsoaresmelero** [comment]
Hi Flávio,
Verify if files that you need are in the address bellow.
[ftp://ftp.datasus.gov.br/dissemin/publicos/](url).
I downloaded CNES files through this address.

**Comment by fccoelho** [comment]
Thanks @rafaelsoaresmelero ! if you want to make a Pull-request with this functionality I'll be glad to accept.

**Comment by fccoelho** [comment]
SINASC and SIH already supported from the FTP server

closing for now
