### ISSUE TITLE
Tratamento de dados faltantes do SIM

### ISSUE THREAD

**Issue by gabrielmcf** [AlertaDengue/PySUS#20]
Acredito que o melhor lugar para implementar isso seja no pré-processamento. A princípio farei para 3 variáveis apenas: município, idade e sexo. O plano é distribuir as mortes com dados faltantes na classe pela proporção observada das entradas com dados completos (sou novo na área de saúde, então posso ter falado bobagem, mas foi o que eu entendi...).

As faixas de idade para o cálculo são variáveis, assim como as regiões que serão consideradas.

**Comment by fccoelho** [comment]
Sim pode ser incluído no préprocessamento, porém, devem ser opcionais. é importante que o usuário possa escolher se deseja este preenchimento ou não. A razão disso é que ele queira prencher os dados faltantes usando sua própria metodologia, ou mesmo estudar o padrão de dados faltantes.

**Comment by gabrielmcf** [comment]
Sim, pensei de fazer uma função separada para isso, se o usuário quiser gerar as tabelas de taxa de mortalidade por municipio/sexo/idade ele pode fazer já preenchendo os dados faltantes ou não.

**Comment by gabrielmcf** [comment]
#25
