### ISSUE TITLE
Large datasets splited in multiple files generate a ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by anapaulagomes** [AlertaDengue/PySUS#201]
Some states have a large data volume during some months, and instead of having only one file, it has a few. The first one is the expected format, and the following is `_<number>.dbc.` I've only tested this for SIA and "Boletins Individualizados." Examples:

```
from pysus.online_data.SIA import download
download('AC', 2019, 1, groups=["BI"])

# or

from pysus.ftp.databases.sia import SIA
sia = SIA().load()
sia.get_files("BI", uf="AL", year=2019)
```

Culprit:
```
BIMG2306.dbc, BIMG2306_1.dbc, BIMG2306_2.dbc
```

PySUS version: 0.14.1
OS: Mac OS M1 / Python 3.11.9

Maybe this is related to https://github.com/AlertaDengue/PySUS/issues/64.
I'd be willing to open a PR with a fix for it; I need a confirmation of what needs to be done here since most `format` methods follow the same return signature.

**Comment by anapaulagomes** [comment]
[Fixed already](https://github.com/AlertaDengue/PySUS/commit/997b41939bc80ce371fb433fb03b9eed18e358ea) but not available in pip.

**Comment by fccoelho** [comment]
@luabida maybe we need a new minor release

**Comment by luabida** [comment]
Sorry for that, I thought it had been published already. It should work now

```py
In [3]: [f for f in sia.get_files("BI") if "_" in f.name]
Out[3]:
[BIMG2305_1.dbc,
 BIMG2305_2.dbc,
 BIMG2306_1.dbc,
 BIMG2306_2.dbc,
 BIMG2307_1.dbc,
 BIMG2307_2.dbc,
 BIMG2308_1.dbc,
 BIMG2308_2.dbc,
 BIMG2309_1.dbc,
 BIMG2309_2.dbc,
 BIMG2310_1.dbc,
 BIMG2310_2.dbc,
 BIMG2311_1.dbc,
 BIMG2311_2.dbc,
 BIMG2312_1.dbc,
 ...
 BISP2405_2.dbc]

In [4]: set([sia.format(f)[1] for f in sia.get_files("BI") if "_" in f.name])
Out[4]: {'MG', 'RJ', 'SP'}


```

**Comment by anapaulagomes** [comment]
It works, thanks!
