### ISSUE TITLE
Tabelas do SIM tem geocode de tamanho variado

### ISSUE THREAD

**Issue by gabrielmcf** [AlertaDengue/PySUS#22]
Abri essa issue para discutir a melhor maneira de resolver essa questão. O código de municípios do IBGE possui 7 dígitos mas em várias tabelas do SIM (SP, 2010, por exemplo) ele é apresentado com apenas 6. Encontrei no site do datasus uma tabela contendo os códigos de municípios utilizados nas bases e creio que talvez o melhor caminho seja seguir essa tabela. A tabela em si pode ser encontrada em ftp://ftp.datasus.gov.br/territorio/tabelas/base_territorial.zip, enquanto o documento com a estrutura está em ftp://ftp.datasus.gov.br/territorio/doc/bases_territoriais.pdf.

Minha sugestão é mudar a função is_valid_geocode para conferir os valores constantes nessa tabela fornecida pelo datasus, ao invés de verificar o sétimo dígito. Esse método tem a vantagem de funcionar também para as tabelas do SIM que possuem apenas 6 dígitos de código de município, que é considerado válido para o datasus.

**Comment by gabrielmcf** [comment]
Vi agora que já tem uma função para baixar os municípios. Não seria melhor usar esse data frame para verificar os geocode?

**Comment by fccoelho** [comment]
A maioria dos bancos do SUS usa apenas 6 digitos. A verificação do 7 digito é importante  pois muitas vezes temos que cruzar informações com outras bases que usam o padrão de 7 dígitos.  Temos também a possibilidade de [adicionar o 7 dígito](https://github.com/AlertaDengue/PySUS/blob/e51d04aa0ae85b619da649ac9b4ec24309c46427/pysus/preprocessing/decoders.py#L100) se necessário. Não vejo necessidade de modificar  a função `is_valid_geocode`. 

Quando à validadação de geocódigos, é mais rápido calcular as funções do que fazer lookup numa tabela de municípios.

**Comment by gabrielmcf** [comment]
Sim, mas se temos uma tabela com código de 6 dígitos e calculamos o geocode pra depois verificar com a mesma conta nunca encontraremos um inválido. A maioria das tabelas usa 6 mas várias não usam. Fiz uma função de olhar na tabela e ficou extremamente rápido, usando as funções certas do pandas. Segue exemplo:

```
def get_valid_geocodes():
    tab_mun = get_municipios()
    df = tab_mun[(tab_mun["SITUACAO"] != "IGNOR")]
    return df["MUNCODDV"].append(df["MUNCOD"]).values

df = download('SP',2006)

valid_mun = get_valid_geocodes()

df["CODMUNRES"] = add_dv(df["CODMUNRES"])
df.loc[~df["CODMUNRES"].isin(valid_mun),"CODMUNRES"] = np.nan
```

Esse código é extremamente performático e garante que se encontrem todos os códigos da tabela que são inválidos. Faço a conversão de todos para 7 dígitos para evitar municípios repetidos (um ano tem 6 dígitos e outro 7, por exemplo).

Concordo que não há necessidade de modificar a função is_valid_geocode, pois ela faz o que diz, mas não é util para encontrar municípios não conhecidos nas tabelas do SIM.

**Comment by fccoelho** [comment]
@gabrielmcf você tem razão de que o cálculo do dígito não serve como validação, pois para qualquer numero de 6 digitos se pode sempre calcular um dígito. O principal uso do `is_valid_geocode` é na verificação de geocódigos de 7 digitos (potencialmente entrados manualmente em alguma base de dados). 

Bola pra frente com a sua implementação!

**Comment by gabrielmcf** [comment]
#25
