### ISSUE TITLE
Update download method of SIA data for PA

### ISSUE THREAD

**Issue by alfonso777** [AlertaDengue/PySUS#27]
Currently, DBC files of SIA data for PA have prefixes a,b and c. The following image show that:
![image](https://user-images.githubusercontent.com/531966/97509026-dfaa4e80-195f-11eb-875f-e32f6aa1b7dc.png)

So, the download method ```pysus.online_data.SIA.download( estado, ano, mes )``` is outdated.

**Comment by fccoelho** [comment]
@alfonso777 how do you suggest he handle these variants? Currently I don't have the time to inspect these datafiles.
