### ISSUE TITLE
Função readdbc com geopandas - gera arquivos dbf que não são apagados

### ISSUE THREAD

**Issue by igorsm88** [AlertaDengue/PySUS#58]
A função read_dbc_geopandas gera um arquivo de saida que se mantém até que o computador seja reiniciado.
Isso gera um problema para programas que fazem download de varios arquivos. Por exemplo 5 anos inteiros do CNES todos os arquivos dbfs são mantidos na pasta temporária.
Exemplo de código:
```python
from pysus.online_data import CNES
from itertools import product

estados = ['RO','AC','AM','RR','PA','AP','TO','MA','PI','CE','RN','PB','PE','AL','SE','BA','MG','ES','RJ','SP','PR','SC','RS','MS','MT','GO','DF']
meses = range(1,13)
anos = range(2006,2011)
grupos = ['ST','LT','DC']
for grupo,estado,ano,mes in product(grupos,estados,anos,meses):
    df = CNES.download(grupo,estado,ano,mes)
```
Função read_dbc_geopandas faz o unlink do arquivo mas ao mesmo tempo gera um .dbf pela variavel out que não é deletado exceto quando o computador é reiniciado
```python
def read_dbc_geopandas(filename, encoding='utf-8'):
    """
    Opens a DATASUS .dbc file and return its contents as a pandas
    Dataframe, using geopandas
    :param filename: .dbc filename
    :param encoding: encoding of the data
    :return: Pandas Dataframe.
    """
    if isinstance(filename, str):
        filename = filename
    with NamedTemporaryFile(delete=False) as tf:
        out = tf.name + '.dbf'
        dbc2dbf(filename, out)
        dbf = gpd.read_file(out, encoding=encoding).drop("geometry", axis=1)
        df = pd.DataFrame(dbf)
    os.unlink(tf.name)

    return df
```
Sugestão fazer o unlink do dbf ao terminar a leitura do dataframe.
```python
def read_dbc_geopandas(filename, encoding='utf-8'):
    """
    Opens a DATASUS .dbc file and return its contents as a pandas
    Dataframe, using geopandas
    :param filename: .dbc filename
    :param encoding: encoding of the data
    :return: Pandas Dataframe.
    """
    if isinstance(filename, str):
        filename = filename
    with NamedTemporaryFile(delete=False) as tf:
        out = tf.name + '.dbf'
        dbc2dbf(filename, out)
        dbf = gpd.read_file(out, encoding=encoding).drop("geometry", axis=1)
        df = pd.DataFrame(dbf)
        os.unlink(out)
    os.unlink(tf.name)

    return df
```

**Comment by fccoelho** [comment]
@igorsm88 Você pode informar  qual SO, versão do Python e versão do PySUS você está usando?

**Comment by igorsm88** [comment]
Boa tarde @fccoelho,

SO:
Ubuntu 20.04.3 LTS
Python versão
Python 3.8.10
Versão do Pysus
Pysus 0.5.10

Você poderia me dizer qual seria a implicação do SO, versão do Python e do versão do PySUS nessa issue? Pois eu não consegui entender qual seria.

**Comment by fccoelho** [comment]
@igorsm88 

Para podermos tentar reproduzir o erro é importante considerar estes fatores.

Acho que o problema já foi resolvido na versão atual de desenvolvimento. Por favor, tente instalar a partir do Github, e veja se o problema persiste.

```bash
pip3 install -U git+https://github.com/AlertaDengue/PySUS.git
```
Note que por padrão, o PySUS mantém um cache dos arquivos já baixados na pasta `/home/<usuario>/pysus/`, no formato `parquet`.
Para inibir este comportamento, você precisa adicionar o argumento `cache=False` na função download:
```python
CNES.download(grupo,estado,ano,mes, cache=False)
```

**Comment by igorsm88** [comment]
Boa tarde @fccoelho,

Essa issue foi resolvida na versão atual de desenvolvimento após essa issue.

Eu entendo que o cache faz isso mas a relação desse issue era com relação aos dbfs gerado no temporário.

Com relação ao cache poderia abrir mais uma issue, pois uma vez que o cache é criado quando você tentar usar o dado mesmo que coloque cache=False ele vai ler o cache. Mas isso seria em outra issue.

**Comment by fccoelho** [comment]
Ok @igorsm88 
Não observei a geração de nenhuma outra cópia dos DBFs 
Caso o problema persista, peço que abra outra issue indicando o `path` onde está sendo criado este DBF adicional.
