### ISSUE TITLE
Problema no download do SIH

### ISSUE THREAD

**Issue by gustavo-mk** [AlertaDengue/PySUS#62]
Atualmente a função download para o SIH só funciona para o ano de 2008.

**Comment by bcbernardo** [comment]
Confirmo o bug, que faz o acesso ao FTP do DataSUS falhar com a mensagem `error_perm: 550 The system cannot find the path specified. `.

Salvo engano, a linha problemática é [esta aqui](https://github.com/AlertaDengue/PySUS/blob/600c61627b7998a1733b71ac163b3de71324cfbe/pysus/online_data/SIH.py#L36). Ela foi modificada em [um commit](https://github.com/AlertaDengue/PySUS/commit/d2bdd2e5beb9780638784aaa66ae985fbae4dc0e) há cerca de 2 meses e passou a apontar para caminhos de diretórios inexistentes do FTP.

Antes:
```py
path = '/dissemin/publicos/SIHSUS/200801_/Dados'.format(year)
```

Agora:
```py
path = f"/dissemin/publicos/SIHSUS/{year}01_/Dados"
```

(se `year` for diferente de 2008, essa variável vai apontar para um diretório inexistente)

@fccoelho - que criou o commit -, creio que a intenção foi apenas trocar o padrão de formatação de strings, correto? Nesse caso me parece que não é necessária nenhuma formatação:

```py
path = '/dissemin/publicos/SIHSUS/200801_/Dados'
```

**Comment by fccoelho** [comment]
I just added a few comments to that PR, @bcbernardo. I point to some alternatives to fix it. The SIH data inthe FTP is quite messy. But we can work around it. login with filezilla and inspec the folders to get the download commands correct for all years:
![image](https://user-images.githubusercontent.com/140123/148699229-082621e6-2476-4f2d-963a-a22cc5c51270.png)
