### ISSUE TITLE
`pysus.online_data.CNES`  type hint return

### ISSUE THREAD

**Issue by aspeddro** [AlertaDengue/PySUS#65]
should the `download` function return a `DataFrame` type?

`_fetch_file` => `DataFrame` and `to_parquet` => `DataFrame`

https://github.com/AlertaDengue/PySUS/blob/600c61627b7998a1733b71ac163b3de71324cfbe/pysus/online_data/CNES.py#L28-L30

**Comment by fccoelho** [comment]
Sure. `object` is a placeholder for any object.
