### ISSUE TITLE
SINAN disease list is incomplete

### ISSUE THREAD

**Issue by gabrielblins** [AlertaDengue/PySUS#71]
The SINAN disease list doesn't have Syphilis!
The SINAN system recorded Syphilis notifications since 2007, is there some reason the Syphilis notifications are not available?

**Comment by fccoelho** [comment]
Hi @gabrielblins , I noticed that the Syphilis data is being shared in a different folder (PRELIM) in the DATASUS server, and it is split by state. We need modify the `sinan` download code to expose the diseases in this PRELIM folder, there are some other diseases there as well.

**Comment by gabrielblins** [comment]
Ok @fccoelho Thanks for the feedback! I will try to work on it this week! :)

**Comment by caibealves** [comment]
@fccoelho Did this happened to the other diseases as well? I was trying to work with Violencia Domestica but no data is available.

**Comment by fccoelho** [comment]
One other this I have just noticed is that the DATASUS changed the aggregation on all SINAN diseases  to be national files. So this, may be the reason that downloads are returning empty. 
For your example @caibealves , it is now `VIOLBR20.dbc` for 2020 data. I'll try to do a quick bug fix of this
